### PR TITLE
ElastiCache/ Redis dashboard

### PR DESCRIPTION
**Pull request by uover822**
AWS ElastiCache/ Redis dashboard, using CloudWatch/ Prometheus (as) datasource.

### CODE REVIEW

**Review by notjames — CHANGES_REQUESTED** [review]
was this tested? Please state so and where.

**Comment by uover822** [comment]
Thanks, Jim :-) I believe this dashboard configuration was recently/ temporarily deployed to uat by @aravind-bluescape but needs to be tested (in atreus) with the current cloudwatch datasource.

**Comment by uover822** [comment]
A current related [dashboard test in atreus](https://grafana.a-atreus.dev.bluescape.io/d/IanMJQd7k-test/aws-elasticache-redis-dashboard-test?orgId=1) seems to work - could folks please review and merge as appropriate? Thanks!

**Comment by thangarajbluescape** [comment]
> A current related [dashboard test in atreus](https://grafana.a-atreus.dev.bluescape.io/d/IanMJQd7k-test/aws-elasticache-redis-dashboard-test?orgId=1) seems to work - could folks please review and merge as appropriate? Thanks!

HI @uover822 Can we resolve the conflicts?

**Comment by uover822** [comment]
Thanks, @thangarajbluescape - conflicts resolved.

**Comment by notjames** [comment]
Looks like we already have redis dashboard(s) in main branch. So closing.

**Pull request closed without merging**
