### PR TITLE
Added new dashboard for msk-exporter - [SRE-138]

### PR DESCRIPTION
**Pull request by thangarajbluescape**
Please review and merge this PR for for msk dashboard.
Tested the changes in dry-run.
helm upgrade --install grafana-dashboards-a-atreus bluescape-monitoring-dashboards -n grafana --dry-run
```
---
# Source: bluescape-monitoring-dashboards/templates/30_msk_exporter/dashboard.yaml
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDashboard
metadata:
  name: msk-exporter-overview-dashboard
  namespace: grafana
  labels:
    helm.sh/chart: bluescape-monitoring-dashboards-0.2.4
    app.kubernetes.io/name: bluescape-monitoring-dashboards
    app.kubernetes.io/instance: grafana-dashboards-a-atreus
    app.kubernetes.io/version: "1.16.2"
    app.kubernetes.io/managed-by: Helm
spec:
  name: msk-exporter-overview-dashboard
  configMapRef:
    name: msk-exporter-overview-dashboard
    key: msk-exporter-overview-dashboard.json
```

### CODE REVIEW

**Review by thomaspretto — COMMENTED** [review]
Looks great, @thangarajbluescape .
Please fix the merge issues and I will approve this change.

**Comment by thangarajbluescape** [comment]
@thomaspretto Resolved the conflicts.

**Review by notjames — CHANGES_REQUESTED** [review]
did you perform the install without `--dry-run`? If not, you should. Once that is successful then I'll approve and merge.

**Comment by thangarajbluescape** [comment]
@notjames I did perform without dry run, And chart was successfully installed without --dry-run.

**Comment by notjames** [comment]
@thangarajbluescape slacked me that he successfully installed in Atreus.

**Review by notjames — APPROVED** [review]
LGTM

**Pull request merged**
