### PR TITLE
[SRE-208] Metric Tracking - Argo CD Health Status Dashboard

### PR DESCRIPTION
**Pull request by uover822**
Metric Tracking - Argo CD Health Status Dashboard. Update source metric name.

### CODE REVIEW

**Review by notjames — CHANGES_REQUESTED** [review]
This PR looks bad. It appears a couple of things are wrong...
 1. There seems to be a new/superfluous template. I don't understand why this is.
 2. It appears that you branched this branch from a non-master because the prometheus exporter is included here, which isn't right. 

This PR is likely going to have to be closed and recreated correctly I think

**Comment by uover822** [comment]
Thanks for this review/ tip, @notjames  :-) I'll reconcile/ recreate.

There isn't a master branch available, but rather `main` - does this make a difference?

If not, then it appears my parent branch may be correct, at least:
```
% git show-branch \
| sed "s/].*//" \
| grep "\*" \
| grep -v "$(git rev-parse --abbrev-ref HEAD)" \
| head -n1 \
| sed "s/^.*\[//"
main
```

**Comment by notjames** [comment]
> Thanks for this review/ tip, @notjames :-) I'll reconcile/ recreate.
> 
> There isn't a master branch available, but rather `main` - does this make a difference?
> 
> If not, then it appears my parent branch may be correct, at least:
> 
> ```
> % git show-branch \
> | sed "s/].*//" \
> | grep "\*" \
> | grep -v "$(git rev-parse --abbrev-ref HEAD)" \
> | head -n1 \
> | sed "s/^.*\[//"
> main
> ```

master v main. The term main or master typically references the same branch in terms of purpose being the default tracking branch for mainline. My point was it looks like you mis-branched this PR and if you didn't...then something is not right about this PR. Ping me OOB to discuss.

**Comment by uover822** [comment]
Thanks, Jim :-) Hi All: I'll redo my branch/ pr and resubmit for (hopefully) a quick/ simple merge.

**Comment by uover822** [comment]
Closing to redo/ refresh/ simplify.

**Pull request closed without merging**
