### PR TITLE
Prometheus cloudwatch exporter - [SRE-191]

### PR DESCRIPTION
**Pull request by thangarajbluescape**
Cloudwatch exporter for prometheus. WIP

### CODE REVIEW

**Comment by npilch** [comment]
@thangarajbluescape @notjames is this a good idea to just copy this all into our own repo?

**Comment by notjames** [comment]
> @thangarajbluescape @notjames is this a good idea to just copy this all into our own repo?

I'd say no. The reason is because the helm charts that get deployed to production get deployed from this repo which doubles as a helm chart repository as well.

**Comment by notjames** [comment]
@thangarajbluescape, is there something custom in this chart that you changed compared to upstream?

**Comment by thangarajbluescape** [comment]
Yes @notjames There are more charts for other exporter, I just used cloudwatch_exporter from that. 
Reference: https://github.com/prometheus-community/helm-charts/tree/main/charts

**Review by uover822 — APPROVED** [review]

**Comment by notjames** [comment]
> https://github.com/prometheus-community/helm-charts/tree/main/charts

So we should be able to just directly `helm install --upgrade prometheus-cloudwatch-exporter prometheus/prometheus-cloudwatch-exporter` from upstream. I don't think we need to keep a copy of it and in fact, we should never keep a copy of it if we don't have to since that would introduce tech debt as we would then need to always keep it updated when upstream changes. By just using upstream, we can determine which version of the chart from upstream to use vs maintaining a local copy of it.

```
$ helm search repo prometheus/
prometheus/prometheus-cloudwatch-exporter       0.16.0          0.10.0          A Helm chart for prometheus cloudwatch-exporter
```

...unless I'm misunderstanding something.

**Comment by kg-ops** [comment]
> > https://github.com/prometheus-community/helm-charts/tree/main/charts
> 
> So we should be able to just directly `helm install --upgrade prometheus-cloudwatch-exporter prometheus/prometheus-cloudwatch-exporter` from upstream. I don't think we need to keep a copy of it and in fact, we should never keep a copy of it if we don't have to since that would introduce tech debt as we would then need to always keep it updated when upstream changes. By just using upstream, we can determine which version of the chart from upstream to use vs maintaining a local copy of it.
> 
> ```
> $ helm search repo prometheus/
> prometheus/prometheus-cloudwatch-exporter       0.16.0          0.10.0          A Helm chart for prometheus cloudwatch-exporter
> ```
> 
> ...unless I'm misunderstanding something.

Unless there are customizations that cannot be added/accommodated - making of a copy of it is extra maintenance that we would want to avoid.

**Comment by thangarajbluescape** [comment]
@kg-ops / @notjames  We don't want this PR, I will close this asap. I'm just keeping it for some reference.

**Pull request closed without merging**
