### PR TITLE
pod distribution dashboard for kubernetes cluster - [SRE-91]

### PR DESCRIPTION
**Pull request by thangarajbluescape**
Please review and merge this PR:
Tested in atreus cluster:
`helm upgrade --install grafana-dashboards-a-atreus bluescape-monitoring-dashboards -n grafana`
```
Release "grafana-dashboards-a-atreus" has been upgraded. Happy Helming!
NAME: grafana-dashboards-a-atreus
LAST DEPLOYED: Fri May 21 14:28:19 2021
NAMESPACE: grafana
STATUS: deployed
REVISION: 3
TEST SUITE: None
```
Dashboard Output: https://grafana.a-atreus.dev.bluescape.io/d/fa49d04ceea0a39f9ba64ed9e72b06137d612c96/kubernetes-cluster-pod-distribution-report?orgId=1&refresh=30s

### CODE REVIEW

**Review by uover822 — APPROVED** [review]
Looks good! Do we version binaries?

**Comment by thangarajbluescape** [comment]
> Looks good! Do we version binaries?

Binaries?

**Comment by uover822** [comment]
Please look under files changed/ at the last file:
image

**Comment by thangarajbluescape** [comment]
> Please look under files changed/ at the last file - guessing it's an archive:
> image

Oh, Thats is created by github-bot, https://github.com/Bluescape/helm-charts/pull/40/commits/e7f37a53a660102ebb88b725d0511da581b40e6d
Basically it will bundle the grafana dashboard folder in tgz formate and push it our PR. So helm deployment use the tgz to install or deploy the dashboard.
Reference github-action:
https://github.com/Bluescape/helm-charts/pull/40/checks?check_run_id=2637878738

**Comment by uover822** [comment]
Got this - thanks, good to know :-)

**Pull request merged**
