### PR TITLE
Feat/tpretto/sre 668 document upload metrics

### PR DESCRIPTION
**Pull request by thomaspretto**
# SRE-668
### Dashboard has:
Document upload histogram metrics:

    upload_full_document
    upload_tika
    upload_pdftron
    upload_pdftron_preview
    upload_virus_scan

For each document upload histogram metric, two panels:

    histogram
    heatmap

 

Addititionally, 

counters: aws_request_count, aws_success, aws_failure

Gauge: worker_status, max_jobs_allowed

### CODE REVIEW

**Review by uover822 — APPROVED** [review]
LGTM, Thomas.

**Review by notjames — COMMENTED** [review]
Topically looks good but is there a link to a dashboard we can view these?

**Comment by thomaspretto** [comment]
> Topically looks good but is there a link to a dashboard we can view these?

https://grafana.b-uat.dev.bluescape.io/d/TbFuG62nz/document-service-uploads

**Review by notjames — APPROVED** [review]
lgtm

**Pull request merged**
