### PR TITLE
[SRE-208] bug/SRE-208/argocd-health-dashboard

### PR DESCRIPTION
**Pull request by uover822**
bug/SRE-208/argocd-health-dashboard - generated/ replaced files.

### CODE REVIEW

**Review by notjames — COMMENTED** [review]
Where was this tested? Please provide a grafana link.

**Comment by uover822** [comment]
Certainly, Jim - here: https://grafana.a-atreus.dev.bluescape.io/d/LCAgc9rWz/delivery-argocd?orgId=1 Let me know of any issues.

**Comment by uover822** [comment]
Hi All: fyi, here's some helm-related deploy tests:

```
% helm upgrade --install grafana-dashboards-a-atreus bluescape-monitoring-dashboards -n grafana
walk.go:74: found symbolic link in path: /opt/helm-charts/helm-chart-sources/bluescape-monitoring-dashboards/add_dashboard resolves to /opt/helm-charts/helm-chart-sources/bluescape-monitoring-dashboards/generate-dashboard
Error: UPGRADE FAILED: no GrafanaDashboard with the name "delivery--argocd-dashboard" found
% helm install grafana-dashboards-a-atreus bluescape-monitoring-dashboards -n grafana 
walk.go:74: found symbolic link in path: /opt/helm-charts/helm-chart-sources/bluescape-monitoring-dashboards/add_dashboard resolves to /opt/helm-charts/helm-chart-sources/bluescape-monitoring-dashboards/generate-dashboard
Error: cannot re-use a name that is still in use
% helm install --replace grafana-dashboards-a-atreus bluescape-monitoring-dashboards -n grafana
walk.go:74: found symbolic link in path: /opt/helm-charts/helm-chart-sources/bluescape-monitoring-dashboards/add_dashboard resolves to /opt/helm-charts/helm-chart-sources/bluescape-monitoring-dashboards/generate-dashboard
Error: cannot patch "delivery--argocd-dashboard" with kind GrafanaDashboard: grafanadashboards.integreatly.org "delivery--argocd-dashboard" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
```

**Comment by thangarajbluescape** [comment]
@uover822 I have faced this kind of problem before, Myself and @notjames discussing about this, There might be workflow error or problem we might need to fix.

**Comment by uover822** [comment]
Thanks for the eyes/ thoughts, @thangarajbluescape. Worst-case, perhaps we could simply copy/ rename/ publish and then remove the old versions.

**Comment by thangarajbluescape** [comment]
Yeah, We can try like that @uover822

**Comment by uover822** [comment]
We met/ discussed issues (possible tool/ env versions contributing?) and upgraded helm to 3.6.2 - here's some additional testing/ dbg'g:

A helm upgrade dry-run succeeds and regular upgrade fails like:
```
% helm upgrade --install grafana-dashboards-a-atreus bluescape-monitoring-dashboards -n grafana          
walk.go:74: found symbolic link in path: /opt/helm-charts/helm-chart-sources/bluescape-monitoring-dashboards/add_dashboard resolves to /opt/helm-charts/helm-chart-sources/bluescape-monitoring-dashboards/generate-dashboard
Error: UPGRADE FAILED: cannot patch "delivery--argocd-dashboard" with kind GrafanaDashboard: grafanadashboards.integreatly.org "delivery--argocd-dashboard" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
```
More to come

**Comment by uover822** [comment]
It works :-) needed to generate/ replace yaml to a single target directory:
```
% helm upgrade --install grafana-dashboards-a-atreus bluescape-monitoring-dashboards -n grafana          
walk.go:74: found symbolic link in path: /opt/helm-charts/helm-chart-sources/bluescape-monitoring-dashboards/add_dashboard resolves to /opt/helm-charts/helm-chart-sources/bluescape-monitoring-dashboards/generate-dashboard
Release "grafana-dashboards-a-atreus" has been upgraded. Happy Helming!
NAME: grafana-dashboards-a-atreus
LAST DEPLOYED: Thu Jul  1 17:08:27 2021
NAMESPACE: grafana
STATUS: deployed
REVISION: 10
TEST SUITE: None
```

**Comment by uover822** [comment]
Tests now pass, so please review/ merge and let me know of any issues.

**Pull request merged**
