### PR TITLE
Prometheus MySQL exporter - [SRE-303]

### PR DESCRIPTION
**Pull request by thangarajbluescape**
Pull this PR from upstream and customise to add serviceAccoutName to run copy-vault container.
Please review and merge this PR.

### CODE REVIEW

**Review by uover822 — APPROVED** [review]
LGTM :-)

**Review by ashwinrajadurai3 — APPROVED** [review]
LGTM

**Review by kg-ops — CHANGES_REQUESTED** [review]
@thangarajbluescape  Is there a reason, why we are importing this chart here - instead of directly using the community hosted chart https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-mysql-exporter ?

**Comment by thangarajbluescape** [comment]
Yes @kg-ops / @notjames we can close this PR, I'm just keep it for some reference, I will close this soon.

**Comment by thangarajbluescape** [comment]
@kg-ops Community chart missing with serviceAccount, There is no templated for creating service account in upstream. So, Actually This chart required service account for accessing vault secret. We customised the chart and updated here.

**Comment by thangarajbluescape** [comment]
@notjames Can we review this PR?

**Comment by ashwinrajadurai3** [comment]
LGTM and i concur customising SA from upstream
Since this is been tested to be working fine in Atreus i'm merging this.

**Comment by notjames** [comment]
@thangarajbluescape I suggest you commit a PR against upstream for the SA change and when they merge it then we can use it instead of committing to managing a local copy of the chart.

**Comment by thangarajbluescape** [comment]
Sure @notjames I will try to add the changes in upstream, Once my changes got merged i will revert back my changes locally.

**Pull request merged**
